### ISSUE TITLE
Proto files without a package not handled properly

### ISSUE THREAD

**Issue by robbertkl** [bojand/grpc-inspect#6]
If a proto file does not contain a `package` (which is perfectly valid), the inspect succeeds, but the results are incorrect. The messages and services end up as namespaces, and functionality like `serviceNames()` always returns `[]`.

**Comment by robbertkl** [comment]
Thanks!

**Comment by bojand** [comment]
This slipped by and forgot about it so took longer. Please see the note in the commit ^.

> **NOTE** If no package name is specified in the protocol buffer definition an empty `''` string is used for the package / namespace name.
